baseURL = 'https://publicdomainrecipes.com'
locale = 'en-us'
title = 'Public Domain Recipes'
theme = 'sugo'

[params]
  indexarticles = 50
  taglist = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
